blank_issues_enabled: false
contact_links:
  - name: Suporte ou dúvidas gerais
    url: https://setimacauda.com.br/contato
    about: Use este canal para dúvidas que não sejam bugs ou sugestões de melhoria.